"""Shell strings for the Audion Get window, keyed by language then label id.

Manifest titles and tooltips are translated in the manifest itself; this file
only carries the text the Python shell prints on its own.
"""

from __future__ import annotations


LABELS: dict[str, dict[str, str]] = {
    "ru": {
        "workspace": "Рабочие папки",
        "operations": "Операции",
        "maintenance": "Обслуживание",
        "status": "Статус",
        "log": "Журнал операции",
        "idle": "Ожидание",
        "running": "Выполняется",
        "done": "Готово",
        "error": "Ошибка",
        "cancel": "Отменить",
        "another_running": "Другая операция уже выполняется.",
        "confirm_title": "Подтвердите действие",
        "confirm_note": "Действие может изменить установленные приложения и компоненты Windows.",
        "run": "ЗАПУСТИТЬ",
        "run_install": "УСТАНОВИТЬ",
        "run_update": "ОБНОВИТЬ",
        "run_uninstall": "УДАЛИТЬ",
        "run_search": "НАЙТИ",
        "run_pin": "ЗАКРЕПИТЬ",
        "run_check": "ПРОВЕРИТЬ",
        "run_export": "ЭКСПОРТ",
        "run_import": "ИМПОРТ",
        "run_add": "ДОБАВИТЬ",
        "run_download": "СКАЧАТЬ",
        "run_link": "ССЫЛКА",
        "run_clean": "ОЧИСТИТЬ",
        "run_build": "СОБРАТЬ",
        "run_enable": "ВКЛЮЧИТЬ",
        "section_vendor": "Производитель",
        "section_build": "Сборка",
        "section_apps": "Приложения в образе",
        "section_versions": "Версии",
        "section_drivers": "Драйверы этой машины",
        "section_registration": "Анкета Blackmagic для бесплатной Resolve",
        "vendor_download_hint": "Скачать только эту сборку в её папку, с докачкой и распаковкой по настройкам ниже.",
        "vendor_download_hint_uupdump": "Собрать образ этой сборки. Готового ISO у Microsoft для отдельных сборок нет: программа берёт пакет скриптов UUP dump, скрипт скачивает оригинальные подписанные файлы с серверов Microsoft (около 9 ГБ) и собирает ISO по настройкам этой вкладки: редакция, приложения, Edge, драйверы. Хотите образ как у Microsoft, оставьте «Как у Microsoft» в приложениях и включите Edge. Сборка идёт в папке UUP в корне диска программы, образ ложится в папку назначения.",
        "gate_adk_missing": "Скачивание закрыто: не установлены Windows ADK Deployment Tools. Без них конвертер UUP dump собирает образ системным DISM, а тот на этой машине не вшивает обновления и редакции. Нажмите «Установить Windows ADK Deployment Tools» внизу.",
        "vendor_download_hint_portable": "Портативная сборка: скачать только этот файл в её папку. Установка не нужна, программа запускается прямо из папки.",
        "vendor_link_hint": "Только получить ссылку на эту сборку и вывести её в журнал, ничего не скачивая.",
        "vendor_link_hint_uupdump": "Ничего не скачивать, а вывести в журнал ссылку на страницу этой сборки на uupdump.net: там те же язык и редакция уже выбраны, и пакет скриптов можно взять вручную, хоть с другой машины.",
        "package_download_title": "Скачать дистрибутив: {package}",
        "package_download_hint": "Скачать установщик WinGet в output\\Downloads, ничего не устанавливая.",
        "package_archive_title": "Скачать архив или portable: {package}",
        "package_archive_hint": "Скачать zip-архив или standalone-сборку в output\\Portable под именем программы; установка не выполняется.",
        "package_page_hint": "Открыть страницу загрузки программы (GitHub Latest, TechPowerUp или сайт разработчика).",
        "package_page_lookup": "Ищу страницу загрузки: {package}",
        "package_page_missing": "Страница загрузки для {package} не найдена.",
        "back": "Назад",
        "selected_operation": "Выбрана команда",
        "open_menu": "Открыть",
        "parameters": "Параметры",
        "section_request": "Запрос",
        "section_provider": "Провайдер",
        "section_prompt": "Prompt",
        "section_generation": "Генерация",
        "section_plan": "План",
        "section_package": "Пакет",
        "section_options": "Опции",
        "ai_tab_planner": "Planner",
        "ai_tab_models": "Models",
        "ai_prompt_actions": "Prompt cache",
        "ai_process_actions": "Действия",
        "ai_pin": "Закрепить",
        "ai_unpin": "Открепить",
        "ai_delete": "Удалить",
        "ai_clear": "Очистить",
        "ai_save": "Сохранить",
        "ai_refresh": "Обновить",
        "ai_check_model": "Проверить модель",
        "ai_build_plan": "Собрать план",
        "ai_run_selected_cta": "Запустить выбранное при помощи AI",
        "prompt_cleared": "Prompt editor очищен.",
        "close": "Закрыть",
        "logs": "Logs",
        "report": "Report",
        "config": "CONFIG",
        "expand": "Развернуть",
        "clear_terminal_window": "Очистить окно терминала",
        "theme": "Тема",
        "theme_saved": "Тема сохранена. Перезагружаю интерфейс.",
        "add_files": "Добавить файлы...",
        "add_folder": "Добавить папку...",
        "source_folder": "Источник",
        "add_file_short": "Добавить файл...",
        "target_folder": "Назначение",
        "clear_io_short": "Сбросить",
        "delete_io_short": "Удалить",
        "file_list_button": "Список",
        "file_list": "File List",
        "file_list_empty": "В ИСТОЧНИКЕ нет файлов.",
        "file_list_missing": "ИСТОЧНИК не найден: {path}",
        "file_list_ready": "File list generated: {count}.",
        "path_required": "Выберите путь.",
        "path_pinned": "Путь закреплен.",
        "path_unpinned": "Путь откреплен.",
        "path_deleted": "Путь удален из истории.",
        "source_selected": "Источник выбран.",
        "target_selected": "Назначение выбрано.",
        "terminal_file": "File",
        "stage_files": "Добавление файлов в input",
        "stage_folder": "Добавление папки в input",
        "picker_cancelled": "Выбор отменен.",
        "operation_done": "Операция завершена.",
        "operation_failed": "Операция завершилась с кодом {code}.",
        "select_required": "Выберите хотя бы один пункт: {field}",
        "refresh_options": "Обновить список",
        "loading_options": "Scanning...",
        "loading_installed_options": "Scanning... WinGet обновляет список установленных ID.",
        "loading_update_options": "Scanning... WinGet проверяет доступные обновления.",
        "no_options": "В этом блоке ничего не найдено.",
        "no_updates": "Обновления отсутствуют",
        "all_installed": "В этом блоке всё уже установлено.",
        "select_group_all": "Отметить блок",
        "select_visible": "Отметить видимое",
        "clear_group": "Снять блок",
        "clear_visible": "Снять видимое",
        "checkbox_filter": "Фильтр",
        "checkbox_filter_placeholder": "Имя или ID",
        "checkbox_filter_count": "{visible}/{total}",
        "checkbox_filter_no_matches": "По фильтру ничего не найдено.",
        "terminal_command": "Команда",
        "terminal_history": "История команд",
        "terminal_history_empty": "Нет сохранённых команд",
        "terminal_location": "Локация",
        "terminal_cwd": "CWD",
        "terminal_shell": "Shell",
        "terminal_run": "Выполнить",
        "pick_folder": "Папка",
        "pick_file": "Файл",
        "terminal_folder": "Папка",
        "terminal_file": "Файл",
        "pin_command": "Закрепить команду",
        "unpin_command": "Открепить команду",
        "clear_terminal_history": "История",
        "clear_history": "История",
        "clear_command_cache": "Кэш",
        "history_cleared": "История команд очищена; закреплённые команды сохранены.",
        "command_cache_cleared": "Кэш команд очищен.",
        "command_required": "Введите команду.",
        "export_checkboxes": "Экспорт YAML",
        "import_checkboxes": "Импорт YAML",
        "checkbox_config_saved": "Выбор сохранён: {path}",
        "checkbox_config_loaded": "Выбор загружен: {path}",
        "checkbox_config_missing": "Файл выбора не найден: {path}",
        "checkbox_config_empty": "В файле нет выбора чекбоксов.",
        "lang_switch": "EN",
    },
    "en": {
        "workspace": "Workspace folders",
        "operations": "Operations",
        "maintenance": "Maintenance",
        "status": "Status",
        "log": "Operation log",
        "idle": "Idle",
        "running": "Running",
        "done": "Done",
        "error": "Error",
        "cancel": "Cancel",
        "another_running": "Another operation is already running.",
        "confirm_title": "Confirm action",
        "confirm_note": "This action may change installed Windows applications and components.",
        "run": "RUN",
        "run_install": "INSTALL",
        "run_update": "UPDATE",
        "run_uninstall": "UNINSTALL",
        "run_search": "SEARCH",
        "run_pin": "PIN",
        "run_check": "CHECK",
        "run_export": "EXPORT",
        "run_import": "IMPORT",
        "run_add": "ADD",
        "run_download": "DOWNLOAD",
        "run_link": "LINK",
        "run_clean": "CLEAN",
        "run_build": "BUILD",
        "run_enable": "ENABLE",
        "section_vendor": "Vendor",
        "section_build": "Build",
        "section_apps": "Apps in the image",
        "section_versions": "Versions",
        "section_drivers": "This machine's drivers",
        "section_registration": "Blackmagic form for the free Resolve",
        "vendor_download_hint": "Download only this build into its folder, resuming and unpacking as set below.",
        "vendor_download_hint_uupdump": "Build the image of this build. Microsoft ships no ready ISO for individual builds: the program takes the UUP dump script package, the script downloads the original signed files from Microsoft's servers (about 9 GB) and assembles the ISO with this tab's settings: edition, apps, Edge, drivers. For an image as Microsoft ships it, keep 'As Microsoft' in apps and switch Edge on. The build runs in the UUP folder at the root of the program's drive, the image lands in the destination folder.",
        "gate_adk_missing": "Download is off: Windows ADK Deployment Tools are not installed. Without them the UUP dump converter builds the image with the system DISM, which on this machine cannot put updates and editions in. Press 'Install Windows ADK Deployment Tools' below.",
        "vendor_download_hint_portable": "Portable build: download only this file into its folder. No installation, the program runs straight from the folder.",
        "vendor_link_hint": "Only resolve the link for this build and print it to the log; nothing is downloaded.",
        "vendor_link_hint_uupdump": "Download nothing; print the link to this build's page on uupdump.net to the log: the same language and edition are preselected there, and the script package can be taken by hand, even from another machine.",
        "package_download_title": "Download installer: {package}",
        "package_download_hint": "Download the WinGet installer into output\\Downloads without installing it.",
        "package_archive_title": "Download archive or portable build: {package}",
        "package_archive_hint": "Download the zip archive or standalone build into output\\Portable under the product name; nothing is installed.",
        "package_page_hint": "Open the download page (GitHub Latest, TechPowerUp or the vendor site).",
        "package_page_lookup": "Looking up the download page: {package}",
        "package_page_missing": "No download page found for {package}.",
        "back": "Back",
        "selected_operation": "Selected command",
        "open_menu": "Open",
        "parameters": "Parameters",
        "section_request": "Request",
        "section_provider": "Provider",
        "section_prompt": "Prompt",
        "section_generation": "Generation",
        "section_plan": "Plan",
        "section_package": "Package",
        "section_options": "Options",
        "ai_tab_planner": "Planner",
        "ai_tab_models": "Models",
        "ai_prompt_actions": "Prompt cache",
        "ai_process_actions": "Actions",
        "ai_pin": "Pin",
        "ai_unpin": "Unpin",
        "ai_delete": "Delete",
        "ai_clear": "Clear",
        "ai_save": "Save",
        "ai_refresh": "Refresh",
        "ai_check_model": "Check model",
        "ai_build_plan": "Build plan",
        "ai_run_selected_cta": "Run selected with AI",
        "prompt_cleared": "Prompt editor cleared.",
        "close": "Close",
        "logs": "Logs",
        "report": "Report",
        "config": "CONFIG",
        "expand": "Expand",
        "clear_terminal_window": "Clear terminal window",
        "theme": "Theme",
        "theme_saved": "Theme saved. Reloading UI.",
        "add_files": "Add files...",
        "add_folder": "Add folder...",
        "add_file_short": "Add file...",
        "source_folder": "Source",
        "target_folder": "Target",
        "clear_io_short": "Reset",
        "delete_io_short": "Delete",
        "file_list_button": "List",
        "file_list": "File List",
        "file_list_empty": "SOURCE has no files.",
        "file_list_missing": "SOURCE was not found: {path}",
        "file_list_ready": "File list generated: {count}.",
        "path_required": "Select a path.",
        "path_pinned": "Path pinned.",
        "path_unpinned": "Path unpinned.",
        "path_deleted": "Path removed from history.",
        "source_selected": "Source selected.",
        "target_selected": "Target selected.",
        "terminal_file": "File",
        "stage_files": "Adding files to input",
        "stage_folder": "Adding folder to input",
        "picker_cancelled": "Selection cancelled.",
        "operation_done": "Operation finished.",
        "operation_failed": "Operation finished with exit code {code}.",
        "select_required": "Select at least one item: {field}",
        "refresh_options": "Refresh list",
        "loading_options": "Scanning...",
        "loading_installed_options": "Scanning... WinGet is updating the installed ID list.",
        "loading_update_options": "Scanning... WinGet is checking available updates.",
        "no_options": "Nothing found in this block.",
        "no_updates": "No updates available",
        "all_installed": "Everything in this block is already installed.",
        "select_group_all": "Select block",
        "select_visible": "Select visible",
        "clear_group": "Clear block",
        "clear_visible": "Clear visible",
        "checkbox_filter": "Filter",
        "checkbox_filter_placeholder": "Name or ID",
        "checkbox_filter_count": "{visible}/{total}",
        "checkbox_filter_no_matches": "No checkbox items match the filter.",
        "terminal_command": "Command",
        "terminal_history": "Command history",
        "terminal_history_empty": "No saved commands",
        "terminal_location": "Location",
        "terminal_cwd": "CWD",
        "terminal_shell": "Shell",
        "terminal_run": "Enter",
        "pick_folder": "Folder",
        "pick_file": "File",
        "terminal_folder": "Folder",
        "terminal_file": "File",
        "pin_command": "Pin",
        "unpin_command": "Unpin",
        "clear_terminal_history": "History",
        "clear_history": "History",
        "clear_command_cache": "Cache",
        "history_cleared": "Command history cleared; pinned commands were kept.",
        "command_cache_cleared": "Command cache cleared.",
        "command_required": "Enter a command.",
        "export_checkboxes": "Export YAML",
        "import_checkboxes": "Import YAML",
        "checkbox_config_saved": "Selection saved: {path}",
        "checkbox_config_loaded": "Selection loaded: {path}",
        "checkbox_config_missing": "Selection file was not found: {path}",
        "checkbox_config_empty": "The file has no checkbox selection.",
        "lang_switch": "RU",
    },
}
